### PR TITLE
Expanding Support for HTTP Methods

### LINKED ISSUE #10: [Feature] Http Method 지원 범위 확대하기
## 기능 상세
- [ ] 추가할 http 메서드
* [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD)
* [CONNECT](https://developer.mozilla.org/enUS/docs/Web/HTTP/Methods/CONNECT)
* [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS)
* [TRACE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/TRACE)
* [PATCH](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH)

### PR DESCRIPTION
**Pull request by lsh23**
## 구현 기능
-  추가한 http 메서드
  - PATCH
  - HEAD
  - CONNECT
  - OPTIONS
  - TRACE

## 기타
```js
  @Head('/api/test')
  head(@Req() req: Request, @Res() res: Response) {
    res.setHeader('myHeader', 'test');
  }

  @Options('/api/test')
  options(@Req() req: Request, @Res() res: Response) {
    res.setHeader('Allow', 'GET, POST, PUT, DELETE');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  }

  @Trace('/api/test')
  trace(@Req() req: Request, @Res() res: Response) {
    const requestHeaders = req.headers;
    return { requestHeaders };
  }
```
코드 실행으로 테스트 진행했습니다.

## Close
- close #10

### CODE REVIEW

**Review by Dltmd202 — APPROVED** [review]
Thank you for your hard work👍
But looking at the example code of PR, I think I should abstract the work of adding headers as well 😭

**Comment by lsh23** [comment]
oh, I've considered that too.

```js
  @Get('/api/test')
  head(@Req() req: Request, @Res() res: Response) {
    const something = getSomething();
    res.setHeader('myHeader', something);
  }
```

but in this case,
if we have @ Headers method decorator that set some values to header,
the something variable is evaluated in the function, we can not use the decorator.

but I agree we should abstract adding of header.

**Comment by Dltmd202** [comment]
Oh I see...
Maybe we can use the MVC pattern's model for dynamic header

```typescript
@Get('/api/test')
head(@Mod() model: Model) {
  model.setHeader()
  const something = getSomething();
  res.setHeader('myHeader', something);
}
```

But I think, In most cases, http header seems to be static.
So we can make this

```typescript
@Heaer('Allow', 'GET, POST, PUT, DELETE')
@Get('/api/test')
head(@Mod() model: Model) {
  model.setHeader()
  const something = getSomething();
  res.setHeader('myHeader', something);
}
```

**Comment by lsh23** [comment]
ok, I will create a issue regarding the relevant features.

**Pull request merged**
